import '../globals.css';
import { Poppins } from 'next/font/google';
import ConditionalNavBar from '../components/layout/NavBar/ConditionalNavBar';
import { Inter } from 'next/font/google';

export const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

// Configure the Inter font
export const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Example weights
  variable: '--font-inter',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${inter.variable}`}>
      <body className="antialiased">
        <ConditionalNavBar />
        {children}
      </body>
    </html>
  );
}
