export const arrivals = [
  {
    productName: 'Loveseat Sofa',
    currentPrice: 199.99,
    originalPrice: 400.0,
    isNew: true,
    discountPercentage: 50,
    rating: 5,
    image: '/images/home/arrivals/arival1.png',
  },
  {
    productName: 'Beig table Lamp',
    currentPrice: 39.99,
    originalPrice: null,
    isNew: true,
    discountPercentage: 27,
    rating: 4.2,
    image: '/images/home/arrivals/arival2.png',
  },
  {
    productName: 'Table Lamp',
    currentPrice: 39.99,
    isNew: true,
    discountPercentage: 50,
    rating: 4.7,
    image: '/images/home/arrivals/arival3.png',
  },
  {
    productName: 'Toasted',
    currentPrice: 129.99,
    originalPrice: 159.99,
    isNew: true,
    discountPercentage: 19,
    rating: 4.8,
    image: '/images/home/arrivals/arival4.png',
  },
  {
    productName: 'Bamboo Basket',
    currentPrice: 9.99,
    originalPrice: null,
    isNew: true,
    discountPercentage: 27,
    rating: 5,
    image: '/images/home/arrivals/arival5.png',
  },

  {
    productName: 'Luxury Sofa',
    currentPrice: 299.99,
    originalPrice: 500,
    isNew: true,
    discountPercentage: 27,
    rating: 4.9,
    image: '/images/home/arrivals/arival6.png',
  },
  {
    productName: 'White Drawer unit',
    currentPrice: 199.99,
    isNew: true,
    discountPercentage: 27,
    rating: 4.9,
    image: '/images/home/arrivals/arival7.png',
  },
  {
    productName: 'Black Tray table',
    currentPrice: 89.99,
    isNew: true,
    discountPercentage: 27,
    rating: 5,
    image: '/images/home/arrivals/arival8.png',
  },
  {
    productName: 'Lamp',
    currentPrice: 39.99,
    isNew: true,
    discountPercentage: 27,
    rating: 5,
    image: '/images/home/arrivals/arival9.png',
  },
  {
    productName: 'Light Beige Pillow',
    currentPrice: 3.99,
    isNew: true,
    discountPercentage: 27,
    rating: 3.4,
    image: '/images/home/arrivals/arival10.png',
  },
];
