import type { Metadata } from 'next';
import '../globals.css';
import { Poppins } from 'next/font/google';
import ConditionalNavBar from '../components/layout/NavBar/ConditionalNavBar';

export const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased">
        <ConditionalNavBar/>
        {children}
      </body>
    </html>
  );
}


